---
- name: A simple file playbook
  hosts: planetexpress
  gather_facts: yes
  connection: ssh

  vars:
    pwd: "{{ ansible_env.HOME }}" 

  tasks:
   - name: make a directory
     file:
       path: ~/output/
       state: directory

# idempotent solution
   - name: use copy instead of a shell command
     copy:
       content: "{{ pwd }}"
       dest: ~/output/path.txt
       force: yes
